version: "2"
services:
  test:
    build: .
    command: npm test
    depends_on:
      - chromeVNC
  chromeVNC:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5901:5900"

  hub:
    image: selenium/hub:3.8.1-chlorine
    ports:
      - "4444:4444"
