version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  set-up:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'run npm install for setup'
  ui:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'run ui-test'
  api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'run api-test'
  report:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'generating report'
workflows:
  ui-api-test:
    jobs:
      - set-up
      - api:
          requires:
            - set-up
      - ui:
          requires:
            - api
      - report:
          requires:
            - ui
