version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  set-up:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i
  ui-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'run ui-test'
  api-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run api-test-ci
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'Deploy code'
  test-reports:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo 'generating report'
workflows:
  ui-api-test-pipeline:
    jobs:
      - set-up
      - api-test:
          requires:
            - set-up
      - ui-test:
          requires:
            - api-test
      - deploy:
          requires:
            - ui-test
      - test-reports:
          requires:
            - ui-test
