version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  set-up:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  ui:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run ui-test
  api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run api-test
workflows:
  ui-api-test:
    jobs:
      - set-up
      - ui:
          requires:
            - set-up
      - api:
          requires:
            - ui
